name: CI
on: [push, pull_request]
jobs:
  build-test:
    uses: cygporter/workflows/.github/workflows/build-test.yml@v1
    with:
      cygport_file: python-flask.cygport
      bootstrap_packages: cygport python38-wheel python39-wheel
